using System.Text;
using ISGPrinter.Application.Abstractions;
using ISGPrinter.Domain.Enums;
using ISGPrinter.Domain.Models;

namespace ISGPrinter.Infrastructure.Reports;

public sealed class PrinterReportService : IPrinterReportService
{
    private const string Divider = "===============================================";
    private const string SubDivider = "-----------------------------------------------";

    public string GenerateTicketReport(PrinterDiagnosticResult result, AppEnvironmentInfo environment)
    {
        var builder = new StringBuilder();
        builder.AppendLine("ISG Printer - Diagnostic Report");
        builder.AppendLine(Divider);
        builder.AppendLine();
        builder.AppendLine(Field("Generated", result.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss zzz")));
        builder.AppendLine(Field("Overall result", OverallText(result.OverallStatus)));
        builder.AppendLine();

        builder.AppendLine("COMPUTER");
        builder.AppendLine(Indent("Name", environment.ComputerName));
        builder.AppendLine(Indent("User", environment.UserName));
        builder.AppendLine(Indent("Domain", Value(environment.DomainName)));
        builder.AppendLine(Indent("Elevated", environment.IsElevated ? "Yes" : "No"));
        builder.AppendLine(Indent("Windows", Value(environment.WindowsVersion)));
        builder.AppendLine();

        builder.AppendLine("PRINTER");
        builder.AppendLine(Indent("Name", Value(result.PrinterName)));
        builder.AppendLine(Indent("UNC", Value(result.UncPath)));
        builder.AppendLine();

        builder.AppendLine("DIAGNOSTIC CHECKS");
        foreach (var check in result.Checks)
        {
            builder.AppendLine($"  [{Tag(check.Status)}] {check.Name.PadRight(18)} {check.Message}");
            if (!string.IsNullOrWhiteSpace(check.TechnicalDetails))
            {
                builder.AppendLine($"          - {check.TechnicalDetails}");
            }
        }

        builder.AppendLine();
        builder.AppendLine("RECOMMENDED STEPS");
        if (result.RecommendedSteps.Count == 0)
        {
            builder.AppendLine("  (none)");
        }
        else
        {
            for (var i = 0; i < result.RecommendedSteps.Count; i++)
            {
                builder.AppendLine($"  {i + 1}. {result.RecommendedSteps[i]}");
            }
        }

        builder.AppendLine();
        builder.AppendLine(SubDivider);
        builder.AppendLine("Report generated by ISG Printer.");
        return builder.ToString();
    }

    private static string Field(string label, string value) => $"{label.PadRight(15)}: {value}";

    private static string Indent(string label, string value) => $"  {label.PadRight(13)}: {value}";

    private static string Value(string value) => string.IsNullOrWhiteSpace(value) ? "(none)" : value;

    private static string Tag(DiagnosticStatus status) => status switch
    {
        DiagnosticStatus.Ok => "OK   ",
        DiagnosticStatus.Warning => "WARN ",
        DiagnosticStatus.Error => "ERROR",
        _ => "--   "
    };

    private static string OverallText(DiagnosticStatus status) => status switch
    {
        DiagnosticStatus.Ok => "OK - no problems found",
        DiagnosticStatus.Warning => "WARNING - review flagged checks",
        DiagnosticStatus.Error => "ERROR - problems found",
        _ => "UNKNOWN"
    };

    public async Task<OperationResult> ExportReportAsync(string reportContent, string filePath, CancellationToken cancellationToken)
    {
        var directory = Path.GetDirectoryName(filePath);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        await File.WriteAllTextAsync(filePath, reportContent, cancellationToken);
        return OperationResult.Ok("Report exported.");
    }
}
